* **コンフィギュレーションオプション**:

  ``app/config/config.yml`` といったファイルでどのようなコンフィギュレーションオプションが使えるのでしょうか。
  ここでは、Symfony2 のコンフィギュレーションで使えるセクションとして定義されているキー(たとえば ``framework``)ごとに、利用可能なすべてのコンフィギュレーションについて解説します。

  * :doc:`framework </reference/configuration/framework>`
  * :doc:`doctrine </reference/configuration/doctrine>`
  * :doc:`security </reference/configuration/security>`
  * :doc:`assetic </reference/configuration/assetic>`
  * :doc:`swiftmailer </reference/configuration/swiftmailer>`
  * :doc:`twig </reference/configuration/twig>`
  * :doc:`monolog </reference/configuration/monolog>`
  * :doc:`web_profiler </reference/configuration/web_profiler>`

* **フォームとバリデーション**

  * :doc:`フォームフィールドタイプリファレンス</reference/forms/types>`
  * :doc:`バリデーション制約リファレンス </reference/constraints>`
  * :doc:`Twig テンプレート関数リファレンス</reference/forms/twig_reference>`

* **その他**

  * :doc:`/reference/dic_tags`
  * :doc:`/reference/requirements`

.. 2012/01/27 hidenorigoto 7771a387c82c396b48cd07482499ea4bfc2a6ef1

