* **コード**:

  * :doc:`バグレポート </contributing/code/bugs>` |
  * :doc:`パッチの投稿 </contributing/code/patches>` |
  * :doc:`セキュリティ問題の報告 </contributing/code/security>` |
  * :doc:`テスト </contributing/code/tests>` |
  * :doc:`コーディング規約 </contributing/code/standards>` |
  * :doc:`ソースコードの慣習 </contributing/code/conventions>` |
  * :doc:`ソースコードのライセンス </contributing/code/license>`

* **ドキュメント**:

  * :doc:`概要 </contributing/documentation/overview>` |
  * :doc:`フォーマット </contributing/documentation/format>` |
  * :doc:`翻訳 </contributing/documentation/translations>` |
  * :doc:`ライセンス </contributing/documentation/license>`

* **コミュニティ**:

  * :doc:`IRCミーティング </contributing/community/irc>` |
  * :doc:`その他のリソース </contributing/community/other>`
